# 1. Basic Settings
site_name: LeetCode Python
site_url: https://lukeclarksf.github.io/leetcode/
site_description: A collection of Python solutions for LeetCode problems with detailed explanations.

# 2. Theme Configuration (Use the Material theme)
theme:
  name: material
  palette:
    scheme: light
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

markdown_extensions:
  # Standard Extensions
  - attr_list
  - admonition
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true # Required for MathJax/KaTeX integration

  # Pymdown Extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  # The configuration file (optional, but good practice)
  - 'mathjax.js' 
  # Load MathJax library from a CDN
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# 3.1 Plugins
plugins:
  - search
  - include-markdown # <--- Add the plugin here

# Inside mkdocs.yml

# ... (other sections like theme, extensions, and plugins) ...

nav:
  - Python:
    - About: 'index.md'
    - Problem 1: '1.md'
    - Problem 2: '2.md'
    - Problem 3: '3.md'
    - Problem 4: '4.md'
    - Problem 5: '5.md'
    - Problem 6: '6.md'
    - Problem 7: '7.md'
    - Problem 8: '8.md'
    - Problem 9: '9.md'
    - Problem 10: '10.md'
    - Problem 11: '11.md'
    - Problem 12: '12.md'
    - Problem 13: '13.md'
    - Problem 14: '14.md'
    - Problem 15: '15.md'
    - Problem 16: '16.md'
    - Problem 17: '17.md'
    - Problem 18: '18.md'
    - Problem 19: '19.md'
    - Problem 20: '20.md'
    - Problem 21: '21.md'
    - Problem 22: '22.md'
    - Problem 23: '23.md'
    - Problem 24: '24.md'
    - Problem 25: '25.md'
    - Problem 26: '26.md'
    - Problem 27: '27.md'
    - Problem 28: '28.md'
    - Problem 29: '29.md'
    - Problem 30: '30.md'
    - Problem 31: '31.md'
    - Problem 32: '32.md'
    - Problem 33: '33.md'
    - Problem 34: '34.md'
    - Problem 35: '35.md'
    - Problem 36: '36.md'
    - Problem 37: '37.md'
    - Problem 38: '38.md'
    - Problem 39: '39.md'
    - Problem 40: '40.md'