site_name: Python
site_url: https://lukeclarkca.com
repo_url: https://github.com/lukeclarksf/leetcode

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy

plugins:
  - monorepo
  - search
  - include-markdown
  - markdown-exec

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/pyodide/v0.29.0/full/pyodide.js
  - javascripts/pyodide_setup.js

  - 'javascripts/mathjax.js'
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
  - Python:
    - Introduction: 'index.md'
    - Gemini: 'https://gemini.google.com'
    - Problems 1 - 1000: '!include python/part1/mkdocs.yml'
    - Problems 1001 - 2000: '!include python/part2/mkdocs.yml'
    - Problems 2001 - 3000: '!include python/part3/mkdocs.yml'
    - Problems 3001 - 3778: '!include python/part4/mkdocs.yml'
  - Gemini: 'https://gemini.google.com'
  - Pyodide: 'pyodide.md'