# 1. Basic Settings
site_name: Python LeetCode
site_url: https://lukeclarkca.com
site_description: A collection of Python solutions for LeetCode problems with detailed explanations.
repo_url: https://github.com/lukeclarksf/leetcode
edit_uri: edit/main/docs/

# 2. Theme Configuration (Use the Material theme)
theme:
  name: material #pyodide-mkdocs-theme #material
  palette:

  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  

extra_css:
  - stylesheets/extra.css


extra_javascript:
  # 1. The main Pyodide library from CDN
  - https://cdn.jsdelivr.net/pyodide/v0.29.0/full/pyodide.js
  
  # 2. Your custom script (path is relative to the 'docs' directory)
  - javascripts/pyodide_setup.js

markdown_extensions:
  # Standard Extensions
  - attr_list
  - admonition
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true # Required for MathJax/KaTeX integration

  # Pymdown Extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
      base_path: [docs/snippets, "."]


extra_javascript:
  # The configuration file (optional, but good practice)
  - 'javascripts/mathjax.js' 
  # Load MathJax library from a CDN
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# 3.1 Plugins
plugins:
  - search
  - projects
  - include-markdown # <--- Add the plugin here
  - markdown-exec
  - mkdocstrings:
     handlers:
      python:
        paths: ['python','python1/part1','python1/part2','python1/part3','python1/part4']

# Inside mkdocs.yml

# ... (other sections like theme, extensions, and plugins) ...

nav:
  #- Part 1: !projects part1/
  #- Part 2: !projects part2/
  #- Part 3: !projects part3/
  #- Part 4: !projects part4/
  - Python:
    - Introduction: 'index.md'
    - Part 0:
      - 1. Two Sum (Easy): '1.md'
      - 2. Add Two Numbers (Medium): '2.md'
      - 3. Longest Substring Without Repeating Characters (Medium): '3.md'
      - 4. Median of Two Sorted Arrays (Hard): '4.md'
      - 5. Longest Palindromic Substring (Medium): '5.md'
      - 6. Zigzag Conversion (Medium): '6.md'
      - 7. Reverse Integer (Easy): '7.md'
      - 8. String to Integer (atoi) (Medium): '8.md'
      - 9. Palindrome Number (Easy): '9.md'
      - 10. Regular Expression Matching (Hard): '10.md'
      - 11. Container With Most Water (Medium): '11.md'
      - 12. Integer to Roman (Medium): '12.md'
      - 13. Roman to Integer (Easy): '13.md'
      - 14. Longest Common Prefix (Easy): '14.md'
      - 15. 3Sum (Medium): '15.md'
      - 16. 3Sum Closest (Medium): '16.md'
      - 17. Letter Combinations of a Phone Number (Medium): '17.md'
      - 18. 4Sum (Medium): '18.md'
      - 19. Remove Nth Node From End of List (Medium): '19.md'
      - 20. Valid Parentheses (Easy): '20.md'
      - 21. Merge Two Sorted Lists (Easy): '21.md'
      - 22. Generate Parentheses (Medium): '22.md'
      - 23. Merge k Sorted Lists (Hard): '23.md'
      - 24. Swap Nodes in Pairs (Medium): '24.md'
      - 25. Reverse Nodes in k-Group (Hard): '25.md'
      - 26. Remove Duplicates from Sorted Array (Easy): '26.md'
      - 27. Remove Element (Easy): '27.md'
      - 28. Find the Index of the First Occurrence in a String (Easy): '28.md'
      - 29. Divide Two Integers (Medium): '29.md'
      - 30. Substring with Concatenation of All Words (Hard): '30.md'
      - 31. Next Permutation (Medium): '31.md'
      - 32. Longest Valid Parentheses (Hard): '32.md'
      - 33. Search in Rotated Sorted Array (Medium): '33.md'
      - 34. Find First and Last Position of Element in Sorted Array (Medium): '34.md'
      - 35. Search Insert Position (Easy): '35.md'
      - 36. Valid Sudoku (Medium): '36.md'
      - 37. Sudoku Solver (Hard): '37.md'
      - 38. Count and Say (Easy): '38.md'
      - 39. Combination Sum (Medium): '39.md'
      - 40. Combination Sum II (Medium): '40.md'
      - 41. First Missing Positive (Hard): '41.md'
      - 42. Trapping Rain Water (Hard): '42.md'
      - 43. Multiply Strings (Medium): '43.md'
      - 44. Wildcard Matching (Hard): '44.md'
      - 45. Jump Game II (Medium): '45.md'
      - 46. Permutations (Medium): '46.md'
      - 47. Permutations II (Medium): '47.md'
      - 48. Rotate Image (Medium): '48.md'
      - 49. Group Anagrams (Medium): '49.md'
      - 50. Pow(x, n) (Medium): '50.md'
      - '51. N-Queens (Hard)': 51.md
      - '52. N-Queens II (Hard)': 52.md
      - '53. Maximum Subarray (Easy)': 53.md
      - '54. Spiral Matrix (Medium)': 54.md
      - '55. Jump Game (Medium)': 55.md
      - '56. Merge Intervals (Medium)': 56.md
      - '57. Insert Interval (Medium)': 57.md
      - '58. Length of Last Word (Easy)': 58.md
      - '59. Spiral Matrix II (Medium)': 59.md
      - '60. Permutation Sequence (Hard)': 60.md
      - '61. Rotate List (Medium)': 61.md
      - '62. Unique Paths (Medium)': 62.md
      - '63. Unique Paths II (Medium)': 63.md
      - '64. Minimum Path Sum (Medium)': 64.md
      - '65. Valid Number (Hard)': 65.md
      - '66. Plus One (Easy)': 66.md
      - '67. Add Binary (Easy)': 67.md
      - '68. Text Justification (Hard)': 68.md
      - '69. Sqrt(x) (Easy)': 69.md
      - '70. Climbing Stairs (Easy)': 70.md
      - '71. Simplify Path (Medium)': 71.md
      - '72. Edit Distance (Hard)': 72.md
      - '73. Set Matrix Zeroes (Medium)': 73.md
      - '74. Search a 2D Matrix (Medium)': 74.md
      - '75. Sort Colors (Medium)': 75.md
      - '76. Minimum Window Substring (Hard)': 76.md
      - '77. Combinations (Medium)': 77.md
      - '78. Subsets (Medium)': 78.md
      - '79. Word Search (Medium)': 79.md
      - '80. Remove Duplicates from Sorted Array II (Medium)': 80.md
      - '81. Search in Rotated Sorted Array II (Medium)': 81.md
      - '82. Remove Duplicates from Sorted List II (Medium)': 82.md
      - '83. Remove Duplicates from Sorted List (Easy)': 83.md
      - '84. Largest Rectangle in Histogram (Hard)': 84.md
      - '85. Maximal Rectangle (Hard)': 85.md
      - '86. Partition List (Medium)': 86.md
      - '87. Scramble String (Hard)': 87.md
      - '88. Merge Sorted Array (Easy)': 88.md
      - '89. Gray Code (Medium)': 89.md
      - '90. Subsets II (Medium)': 90.md
      - '91. Decode Ways (Medium)': 91.md
      - '92. Reverse Linked List II (Medium)': 92.md
      - '93. Restore IP Addresses (Medium)': 93.md
      - '94. Binary Tree Inorder Traversal (Easy)': 94.md
      - '95. Unique Binary Search Trees II (Medium)': 95.md
      - '96. Unique Binary Search Trees (Medium)': 96.md
      - '97. Interleaving String (Hard)': 97.md
      - '98. Validate Binary Search Tree (Medium)': 98.md
      - '99. Recover Binary Search Tree (Medium)': 99.md
      - '100. Same Tree (Easy)': 100.md
  - Pyodide: 'pyodide.md'
  - Gemini: 'https://gemini.google.com/'
  - Vitae: 'https://lukeclarksf.com'