site_name: Python

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy

plugins:
  - monorepo
  - search
  - include-markdown
  - markdown-exec
  - mkdocstrings:
      handlers:
      python:
        paths: ['python/part1/python','python/part2/python','python/part3/python','python/part4/python']

markdown_extensions:
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/pyodide/v0.29.0/full/pyodide.js
  - javascripts/pyodide_setup.js

nav:
  - Python:
    - Introduction: 'index.md'
    - Gemini: 'https://gemini.google.com'
    - Problems 1 - 1000: '!include python/part1/mkdocs.yml'
    - Problems 1001 - 2000: '!include python/part2/mkdocs.yml'
    - Problems 2001 - 3000: '!include python/part3/mkdocs.yml'
    - Problems 3001 - 3778: '!include python/part4/mkdocs.yml'
  - Gemini: 'https://gemini.google.com'
  - Pyodide: 'pyodide.md'