# 1. Basic Settings
site_name: LeetCode Python
site_url: https://lukeclarksf.github.io/leetcode/
site_description: A collection of Python solutions for LeetCode problems with detailed explanations.

# 2. Theme Configuration (Use the Material theme)
theme:
  name: material
  palette:
    scheme: light
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  # Standard Extensions
  - attr_list
  - admonition
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true # Required for MathJax/KaTeX integration

  # Pymdown Extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  # The configuration file (optional, but good practice)
  - 'mathjax.js' 
  # Load MathJax library from a CDN
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# 3.1 Plugins
plugins:
  - search
  - include-markdown # <--- Add the plugin here

# Inside mkdocs.yml

# ... (other sections like theme, extensions, and plugins) ...

nav:
  - Python:
    - About: 'index.md'
    - 1. (Easy) Two Sum: '1.md'
    - 2. (Medium) Add Two Numbers: '2.md'
    - 3. (Medium) Longest Substring Without Repeating Characters: '3.md'
    - 4. (Hard) Median of Two Sorted Arrays: '4.md'
    - 5. (Medium) Longest Palindromic Substring: '5.md'
    - 6. (Medium) Zigzag Conversion: '6.md'
    - 7. (Medium) Reverse Integer: '7.md'
    - 8. (Medium) String to Integer (atoi): '8.md'
    - 9. (Easy) Palindrome Number: '9.md'
    - 10. (Hard) Regular Expression Matching: '10.md'
    - 11. (Medium) Container With Most Water: '11.md'
    - 12. (Medium) Integer to Roman: '12.md'
    - 13. (Easy) Roman to Integer: '13.md'
    - 14. (Easy) Longest Common Prefix: '14.md'
    - 15. (Medium) 3Sum: '15.md'
    - 16. (Medium) 3Sum Closest: '16.md'
    - 17. (Medium) Letter Combinations of a Phone Number: '17.md'
    - 18. (Medium) 4Sum: '18.md'
    - 19. (Medium) Remove Nth Node From End of List: '19.md'
    - 20. (Easy) Valid Parentheses: '20.md'
    - 21. (Easy) Merge Two Sorted Lists: '21.md'
    - 22. (Medium) Generate Parentheses: '22.md'
    - 23. (Hard) Merge k Sorted Lists: '23.md'
    - 24. (Medium) Swap Nodes in Pairs: '24.md'
    - 25. (Hard) Reverse Nodes in k-Group: '25.md'
    - 26. (Easy) Remove Duplicates from Sorted Array: '26.md'
    - 27. (Easy) Remove Element: '27.md'
    - 28. (Easy) Find the Index of the First Occurrence in a String (Implement strStr()): '28.md'
    - 29. (Medium) Divide Two Integers: '29.md'
    - 30. (Hard) Substring with Concatenation of All Words: '30.md'
    - 31. (Medium) Next Permutation: '31.md'
    - 32. (Hard) Longest Valid Parentheses: '32.md'
    - 33. (Medium) Search in Rotated Sorted Array: '33.md'
    - 34. (Medium) Find First and Last Position of Element in Sorted Array: '34.md'
    - 35. (Easy) Search Insert Position: '35.md'
    - 36. (Medium) Valid Sudoku: '36.md'
    - 37. (Hard) Sudoku Solver: '37.md'
    - 38. (Medium) Count and Say: '38.md'
    - 39. (Medium) Combination Sum: '39.md'
    - 40. (Medium) Combination Sum II: '40.md'
    - 41. (Hard) First Missing Positive: '41.md'
    - 42. (Hard) Trapping Rain Water: '42.md'
    - 43. (Medium) Multiply Strings: '43.md'
    - 44. (Hard) Wildcard Matching: '44.md'
    - 45. (Medium) Jump Game II: '45.md'
    - 46. (Medium) Permutations: '46.md'
    - 47. (Medium) Permutations II: '47.md'
    - 48. (Medium) Rotate Image: '48.md'
    - 49. (Medium) Group Anagrams: '49.md'
    - 50. (Medium) Pow(x, n): '50.md'
    - 51. (Hard) N-Queens: '51.md'
    - 52. (Hard) N-Queens II: '52.md'
    - 53. (Medium) Maximum Subarray: '53.md'
    - 54. (Medium) Spiral Matrix: '54.md'
    - 55. (Medium) Jump Game: '55.md'
    - 56. (Medium) Merge Intervals: '56.md'
    - 57. (Medium) Insert Interval: '57.md'
    - 58. (Easy) Length of Last Word: '58.md'
    - 59. (Medium) Spiral Matrix II: '59.md'
    - 60. (Hard) Permutation Sequence: '60.md'
    - 61. (Medium) Rotate List: '61.md'
    - 62. (Medium) Unique Paths: '62.md'
    - 63. (Medium) Unique Paths II: '63.md'
    - 64. (Medium) Minimum Path Sum: '64.md'
    - 65. (Hard) Valid Number: '65.md'
    - 66. (Easy) Plus One: '66.md'
    - 67. (Easy) Add Binary: '67.md'
    - 68. (Hard) Text Justification: '68.md'
    - 69. (Easy) Sqrt(x): '69.md'
    - 70. (Easy) Climbing Stairs: '70.md'
    - 71. (Medium) Simplify Path: '71.md'
    - 72. (Hard) Edit Distance: '72.md'
    - 73. (Medium) Set Matrix Zeroes: '73.md'
    - 74. (Medium) Search a 2D Matrix: '74.md'
    - 75. (Medium) Sort Colors: '75.md'
    - 76. (Hard) Minimum Window Substring: '76.md'
    - 77. (Medium) Combinations: '77.md'
    - 78. (Medium) Subsets: '78.md'
    - 79. (Medium) Word Search: '79.md'
    - 80. (Medium) Remove Duplicates from Sorted Array II: '80.md'
    - 81. (Medium) Search in Rotated Sorted Array II: '81.md'
    - 82. (Medium) Remove Duplicates from Sorted List II: '82.md'
    - 83. (Easy) Remove Duplicates from Sorted List: '83.md'
    - 84. (Hard) Largest Rectangle in Histogram: '84.md'
    - 85. (Hard) Maximal Rectangle: '85.md'
    - 86. (Medium) Partition List: '86.md'
    - 87. (Hard) Scramble String: '87.md'
    - 88. (Easy) Merge Sorted Array: '88.md'
    - 89. (Medium) Gray Code: '89.md'
    - 90. (Medium) Subsets II: '90.md'
    - 91. (Medium) Decode Ways: '91.md'
    - 92. (Medium) Reverse Linked List II: '92.md'
    - 93. (Medium) Restore IP Addresses: '93.md'
    - 94. (Easy) Binary Tree Inorder Traversal: '94.md'
    - 95. (Medium) Unique Binary Search Trees II: '95.md'
    - 96. (Medium) Unique Binary Search Trees: '96.md'
    - 97. (Medium) Interleaving String: '97.md'
    - 98. (Medium) Validate Binary Search Tree: '98.md'
    - 99. (Medium) Recover Binary Search Tree: '99.md'
    - 100. (Easy) Same Tree: '100.md'
    - 101. (Easy) Symmetric Tree: '101.md'
    - 102. (Medium) Binary Tree Level Order Traversal: '102.md'
    - 103. (Medium) Binary Tree Zigzag Level Order Traversal: '103.md'
    - 104. (Easy) Maximum Depth of Binary Tree: '104.md'
    - 105. (Medium) Construct Binary Tree from Preorder and Inorder Traversal: '105.md'
    - 106. (Medium) Construct Binary Tree from Inorder and Postorder Traversal: '106.md'
    - 107. (Easy) Binary Tree Level Order Traversal II: '107.md'
    - 108. (Easy) Convert Sorted Array to Binary Search Tree: '108.md'
    - 109. (Medium) Convert Sorted List to Binary Search Tree: '109.md'
    - 110. (Easy) Balanced Binary Tree: '110.md'
    - 111. (Easy) Minimum Depth of Binary Tree: '111.md'
    - 112. (Easy) Path Sum: '112.md'
    - 113. (Medium) Path Sum II: '113.md'
    - 114. (Medium) Flatten Binary Tree to Linked List: '114.md'
    - 115. (Hard) Distinct Subsequences: '115.md'
    - 116. (Medium) Populating Next Right Pointers in Each Node: '116.md'
    - 117. (Medium) Populating Next Right Pointers in Each Node II: '117.md'
    - 118. (Easy) Pascal's Triangle: '118.md'
    - 119. (Easy) Pascal's Triangle II: '119.md'
    - 120. (Medium) Triangle: '120.md'    
    - 121. (Easy) Best Time to Buy and Sell Stock: '121.md'
    - 122. (Medium) Best Time to Buy and Sell Stock II: '122.md'
    - 123. (Hard) Best Time to Buy and Sell Stock III: '123.md'
    - 124. (Hard) Binary Tree Maximum Path Sum: '124.md'
    - 125. (Easy) Valid Palindrome: '125.md'
    - 126. (Hard) Word Ladder II: '126.md'
    - 127. (Medium) Word Ladder: '127.md'
    - 128. (Medium) Longest Consecutive Sequence: '128.md'
    - 129. (Medium) Sum Root to Leaf Numbers: '129.md'
    - 130. (Medium) Surrounded Regions: '130.md'
    - 131. (Medium) Palindrome Partitioning: '131.md'
    - 132. (Hard) Palindrome Partitioning II: '132.md'
    - 133. (Medium) Clone Graph: '133.md'
    - 134. (Medium) Gas Station: '134.md'
    - 135. (Hard) Candy: '135.md'
    - 136. (Easy) Single Number: '136.md'
    - 137. (Medium) Single Number II: '137.md'
    - 138. (Medium) Copy List with Random Pointer: '138.md'
    - 139. (Medium) Word Break: '139.md'
    - 140. (Hard) Word Break II: '140.md'
    - 141. (Easy) Linked List Cycle: '141.md'
    - 142. (Medium) Linked List Cycle II: '142.md'
    - 143. (Medium) Reorder List: '143.md'
    - 144. (Easy) Binary Tree Preorder Traversal: '144.md'
    - 145. (Easy) Binary Tree Postorder Traversal: '145.md'
    - 146. (Medium) LRU Cache: '146.md'
    - 147. (Medium) Insertion Sort List: '147.md'
    - 148. (Medium) Sort List: '148.md'
    - 149. (Hard) Max Points on a Line: '149.md'
    - 150. (Medium) Evaluate Reverse Polish Notation: '150.md'
    - 151. (Medium) Reverse Words in a String: '151.md'
    - 152. (Medium) Maximum Product Subarray: '152.md'
    - 153. (Medium) Find Minimum in Rotated Sorted Array: '153.md'
    - 154. (Hard) Find Minimum in Rotated Sorted Array II: '154.md'
    - 155. (Easy) Min Stack: '155.md'
    - 156. (Medium) Binary Tree Upside Down (Locked): '156.md'
    - 157. (Easy) Read N Characters Given Read4 (Locked): '157.md'
    - 158. (Medium) Read N Characters Given Read4 II - Call multiple times (Locked): '158.md'
    - 159. (Medium) Longest Substring with At Most Two Distinct Characters (Locked): '159.md'
    - 160. (Easy) Intersection of Two Linked Lists: '160.md'